// Emit the layout tables for docs/FINAL-LAYOUT.md straight from the code.
//
// This exists because the docs drifted from the geometry: FINAL-LAYOUT.md
// carried a transposed bathroom, a hall half a foot too narrow, a total 65 sq ft
// light, and no mention of the closets at all. Hand-maintaining duplicates of
// computed numbers is exactly how "54 x 151" survived across three artifacts.
//
//   node scripts/emit-layout.mjs

import { buildSuite, DEFAULT_PARAMS } from "../src/geo/rooms.ts";
import { buildWalls, footprintArea } from "../src/geo/walls.ts";

const suite = buildSuite();
const { walls, openings } = buildWalls(suite);

const f = (n) => (Number.isInteger(n) ? String(n) : n.toFixed(2).replace(/\.?0+$/, ""));

console.log("<!-- generated by scripts/emit-layout.mjs, do not edit by hand -->\n");
console.log("| Room | Size, ft | Area, sq ft | Basis |");
console.log("|---|---|---|---|");
for (const r of suite.rooms) {
  console.log(
    `| ${r.label} | ${f(r.du)} x ${f(r.dv)} | ${f(r.du * r.dv)} | ${r.stated ?? "derived"} |`,
  );
}
console.log(`| **the resident's five rooms** | | **${f(suite.roomArea)}** | |`);
console.log(
  `| **With hall and closets** | | **${f(suite.netArea)}** | ${f(suite.netArea / 4)} per person for four |`,
);

console.log("\n| Quantity | Value | Source |");
console.log("|---|---|---|");
const p = DEFAULT_PARAMS;
for (const [a, b, c] of [
  ["End section length", `${f(p.sectionLength)} ft`, "1875 spec: 143 less two 15 ft stair halls and a 25 ft porch, halved"],
  ["Main leg depth", `${f(p.legDepth)} ft`, "hall + partition + bedroom depth"],
  ["Hall width", `${f(p.hallWidth)} ft`, "inferred"],
  ["Bedroom depth", `${f(p.bedDepth)} ft`, "given"],
  ["Bathroom", `${f(p.bathAlong)} x ${f(p.bathDeep)} ft`, "inferred, bounded 6-8 ft"],
  ["Partition / masonry", `${f(p.partition)} / ${f(p.masonry)} ft`, "inferred"],
  ["Ceiling", `${f(p.ceiling)} ft`, "12 ft floor-to-floor less the floor assembly"],
  ["Facade", p.facade, "default; toggleable"],
]) {
  console.log(`| ${a} | ${b} | ${c} |`);
}

console.log(
  `\nResiduals at defaults: along ${suite.residuals.along}, across ${suite.residuals.across}.`,
);
console.log(
  `Gross footprint ${f(footprintArea(suite))} sq ft. Reaches ${f(suite.maxDepth)} ft inward at the K bump, of the section's 51 ft.`,
);
console.log(
  `${walls.filter((w) => !w.perimeter).length} interior wall bands, ${walls.filter((w) => w.perimeter).length} perimeter bands, ${openings.length} openings.`,
);
